name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install npm dependencies
      run: npm ci
      
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        
    - name: Debug - List files
      run: |
        echo "Current directory:"
        pwd
        echo "Files in root:"
        ls -la
        echo "Files in android directory:"
        ls -la android/
        
    - name: Make gradlew executable
      run: |
        chmod +x android/gradlew
        ls -la android/gradlew
        
    - name: Build Release APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleRelease --stacktrace
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: di2-erg-training-app-release
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30